// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKqD-0d0tYRr8G3p3Khziwh4HxGllvKss',
    appId: '1:967768444780:web:3a526f0120dffd975bed49',
    messagingSenderId: '967768444780',
    projectId: 'bar-gpt',
    authDomain: 'bar-gpt.firebaseapp.com',
    storageBucket: 'bar-gpt.appspot.com',
    measurementId: 'G-CH44J7HPVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy0eziaH19ezdeUcpxf-btF142NxT4QVo',
    appId: '1:967768444780:android:f473dde14ec29f7e5bed49',
    messagingSenderId: '967768444780',
    projectId: 'bar-gpt',
    storageBucket: 'bar-gpt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt2y-rz_MhBm3G3egUq7-z2YRbb8fCdYg',
    appId: '1:967768444780:ios:42121434fd3e6e1b5bed49',
    messagingSenderId: '967768444780',
    projectId: 'bar-gpt',
    storageBucket: 'bar-gpt.appspot.com',
    iosClientId: '967768444780-horphjoe04j4vh1rcerognvj4gof5v7v.apps.googleusercontent.com',
    iosBundleId: 'com.lawi.barGpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt2y-rz_MhBm3G3egUq7-z2YRbb8fCdYg',
    appId: '1:967768444780:ios:42121434fd3e6e1b5bed49',
    messagingSenderId: '967768444780',
    projectId: 'bar-gpt',
    storageBucket: 'bar-gpt.appspot.com',
    iosClientId: '967768444780-horphjoe04j4vh1rcerognvj4gof5v7v.apps.googleusercontent.com',
    iosBundleId: 'com.lawi.barGpt',
  );
}
