// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `answer.dart` with the code generated by Freezed
part 'answer.freezed.dart';
// optional: Since our Answer class is serializable, we must add this line.
// But if Answer was not serializable, we could skip it.
part 'answer.g.dart';

@freezed
class Answer with _$Answer {
  const factory Answer({
    required int id,
    required String content,
    @JsonKey(name: 'reference_urls') required List<String>? referenceUrls,
  }) = _Answer;

  factory Answer.fromJson(Map<String, Object?> json)
      => _$AnswerFromJson(json);
}