// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `exam.dart` with the code generated by Freezed
part 'exam.freezed.dart';
// optional: Since our Exam class is serializable, we must add this line.
// But if Exam was not serializable, we could skip it.
part 'exam.g.dart';

@freezed
class Exam with _$Exam {
  const factory Exam({
    required int id,
    required int num,
    required int year,
    required String category,
    required String type,
  }) = _Exam;

  factory Exam.fromJson(Map<String, Object?> json)
      => _$ExamFromJson(json);
}