// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `passage.dart` with the code generated by Freezed
part 'passage.freezed.dart';
// optional: Since our Passage class is serializable, we must add this line.
// But if Passage was not serializable, we could skip it.
part 'passage.g.dart';

@freezed
class Passage with _$Passage {
  const factory Passage({
    required int id,
    required String content,
    required String? tag,
    required int? order,
    @JsonKey(name: 'has_questions') required bool hasQuestions,
  }) = _Passage;

  factory Passage.fromJson(Map<String, Object?> json)
      => _$PassageFromJson(json);
}