// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `question_group.dart` with the code generated by Freezed
part 'question_group.freezed.dart';
// optional: Since our QuestionGroup class is serializable, we must add this line.
// But if QuestionGroup was not serializable, we could skip it.
part 'question_group.g.dart';

@freezed
class QuestionGroup with _$QuestionGroup {
  const factory QuestionGroup({
    required int id,
    required String label,
  }) = _QuestionGroup;

  factory QuestionGroup.fromJson(Map<String, Object?> json)
      => _$QuestionGroupFromJson(json);
}