// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `question.dart` with the code generated by Freezed
part 'question.freezed.dart';
// optional: Since our Question class is serializable, we must add this line.
// But if Question was not serializable, we could skip it.
part 'question.g.dart';

@freezed
class Question with _$Question {
  const factory Question({
    required int id,
    required String content,
    @JsonKey(name: 'total_score') required int? totalScore,
    @JsonKey(name: 'exam_id') required int? examId,
    required int? num,
    required bool supported,
  }) = _Question;

  factory Question.fromJson(Map<String, Object?> json) =>
      _$QuestionFromJson(json);
}
